### ISSUE TITLE
Dependency on private repository

### ISSUE THREAD

**Issue by jenrik** [neticdk-k8s/ic#4]
We currently depends on `github.com/neticdk/go-common` which is private, meaning this repository can not be build if your not part of the neticdk organization.

**Comment by langecode** [comment]
As I understand it this about being able to package the command line? I think maybe we should create a gh action that triggers on the creation of new releases and build binaries for arm and amd64 for downloads. That would eliminate the need to know the magic of private go modules (and having a token in git "keychain")

**Comment by jenrik** [comment]
not really, I'm trying to create a Nix deriviation to install `ic` and Nix doesn't really play nice with private repositories. I will try to workaround the issue, but it is a bit of a nuance that you can't build from source.
